services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: fusion_flow:latest
    restart: always
    env_file:
      - path: .env
        required: false
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/fusion_flow
      - UI_POOL_SIZE=10
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - PHX_HOST=localhost
      - PORT=4000
      - PHX_SERVER=true
      - FUSION_FLOW_MODE=ui
    ports:
      - "4000:4000"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: fusion_flow:latest
    restart: always
    env_file:
      - path: .env
        required: false
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/fusion_flow
      - WORKER_POOL_SIZE=3
      - OBAN_DEFAULT_CONCURRENCY=2
      - OBAN_EXECUTIONS_CONCURRENCY=5
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - FUSION_FLOW_MODE=worker
    depends_on:
      - db

  all:
    profiles: ["all"]
    build:
      context: .
      dockerfile: Dockerfile
    image: fusion_flow:latest
    restart: always
    env_file:
      - path: .env
        required: false
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/fusion_flow
      - UI_POOL_SIZE=10
      - WORKER_POOL_SIZE=3
      - OBAN_DEFAULT_CONCURRENCY=2
      - OBAN_EXECUTIONS_CONCURRENCY=5
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - PHX_HOST=localhost
      - PORT=4000
      - PHX_SERVER=true
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: fusion_flow_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fusion_flow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
